### ISSUE TITLE
how to get output images after running run_detector.py

### ISSUE THREAD

**Issue by mrtechnoo** [delmalih/one_shot_classification_and_detection#3]

**Comment by delmalih** [comment]
There is a `--output_path` flag and you can set the output directory.
NB: This repo is deprecated, another one will come very soon :)

**Comment by mrtechnoo** [comment]
i can only get  matcher-classifier-custom.hnsw and matcher-detector.hnsw to the path of --output_path

**Comment by delmalih** [comment]
These files are supposed to be in the `./files` folder. Unless you've set `--output-path` to be `./files`, you're supposed to get your results in this folder.

Example:
```
python run_detector.py -ci ./data/catalog \
                       -qi ./data/query_images \
                       -o ./data/output
```

Your results will be in `./data/output`
